### ISSUE TITLE
[Bug]: AgentDelegation to ManagerAgent doesn't support inputs

### ISSUE THREAD

**Issue by AlexCuadron** [All-Hands-AI/OpenHands#4426]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Modify the `PlannerAgent`to delegate to a micro agent (eg. ManagerAgent) and provide a specific task like so:
```
return AgentDelegateAction(
          agent='ManagerAgent', inputs={'task': 'Investigate the current SQLFluff CLI documentation and source code to understand how verbosity levels are currently implemented. Identify if there are any existing flags or settings that can be adjusted to reduce verbosity.'}
)
```
This should be supported as the yaml definition of `ManagerAgent` is as follows:
```
name: ManagerAgent
description: Delegates tasks to microagents based on their area of expertise
generates: Action
inputs:
  task: string #It takes a string as input.
outputs:
  summary: string # if finished
  reason: string # if rejected
```

However, during the execution, this is the prompt the LLM gets from the micro-agent:
```
# Task
You are in charge of accomplishing the following task:
None

In order to accomplish this goal, you must delegate tasks to one or more agents, who
can do the actual work. A description of each agent is provided below. You MUST
select one of the delegates below to move towards accomplishing the task, and you MUST
provide the correct inputs for the delegate you select.
... rest of the file ...
```
Instead of `None` it should provide the input from the delegate action.

### OpenHands Installation

Development workflow

### OpenHands Version

0.9.8

### Operating System

MacOS
