### ISSUE TITLE
[Resolver] Pass retry logic environment variables in GitHub Action 

### ISSUE THREAD

**Issue by FabianHertwig** [All-Hands-AI/OpenHands#5087]
**What problem or use case are you trying to solve?**

When using the OpenHands Resolver with Claude I run into rate limit errors most of the time.

**Describe the UX of the solution you'd like**

I would like to be able to pass the rate limit configuration to the GitHub Action 

**Do you have thoughts on the technical implementation?**

I would like to add 

      LLM_RETRY_MIN_WAIT: 60
      LLM_RETRY_MAX_WAIT: 600

to my workflow like in the example below:

```yml
jobs:
  call-openhands-resolver:
    if: |
      ${{
        github.event.label.name == 'fix-me' ||
        (github.event_name == 'issue_comment' &&
        startsWith(github.event.comment.body, vars.OPENHANDS_MACRO || '@openhands-agent') &&
        (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'MEMBER'))
      }}
    uses: All-Hands-AI/OpenHands/.github/workflows/openhands-resolver.yml@main
    with:
      macro: ${{ vars.OPENHANDS_MACRO || '@openhands-agent' }}
      max_iterations: 50
      LLM_RETRY_MIN_WAIT: 60
      LLM_RETRY_MAX_WAIT: 600
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
```

Ideally the other configuration values are also supported
    
    LLM_NUM_RETRIES (Default of 8)
    LLM_RETRY_MIN_WAIT (Default of 15 seconds)
    LLM_RETRY_MAX_WAIT (Default of 120 seconds)
    LLM_RETRY_MULTIPLIER (Default of 2)

I think in the `All-Hands-AI/OpenHands/.github/workflows/openhands-resolver.yml` they must then be added as inputs and passed on with the other env variables. 

https://github.com/All-Hands-AI/OpenHands/blob/104f52bcdd4859c68d241a00d4f46d0bad658572/.github/workflows/openhands-resolver.yml#L3-L24

https://github.com/All-Hands-AI/OpenHands/blob/104f52bcdd4859c68d241a00d4f46d0bad658572/.github/workflows/openhands-resolver.yml#L150-L164
