### ISSUE TITLE
[Bug]: WebSocket Crashes with ValueError on `latest_event_id`

### ISSUE THREAD

**Issue by liatweissman** [All-Hands-AI/OpenHands#5151]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### **Description:**
I'm encountering a critical issue while integrating OpenHands with LiteLLM Proxy to access Amazon Bedrock. The WebSocket crashes repeatedly due to a `ValueError` when OpenHands attempts to process the query parameter `latest_event_id`. This seems to occur because the value of `latest_event_id` is `'undefined'`, which cannot be converted to an integer.

---

### **Steps to Reproduce:**
1. Configure LiteLLM Proxy with the following `config.yaml`:
    ```yaml
    model_list:
      - model_name: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
        litellm_params:
          model: "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
          aws_region_name: us-east-1
        model_info:
          id: "arn:aws:bedrock:us-east-1:6xxxxxxxxx8:inference-profile/us.anthropic.claude-3-5-sonnet-20241022-v2:0"

    general_settings:
      master_key: sk-xxxxxxxxx
    ```

2. Start the LiteLLM Proxy:
    ```bash
    export AWS_ACCESS_KEY_ID=your-access-key-id
    export AWS_SECRET_ACCESS_KEY=your-secret-access-key
    export AWS_REGION=us-east-1
    litellm --debug --config ./config.yaml
    ```

3. Verify that the LiteLLM Proxy works by making the following API call:
    ```bash
    curl --location 'http://0.0.0.0:4000/chat/completions' \
      --header 'Content-Type: application/json' \
      -H 'Authorization: Bearer sk-xxxxxxxx' \
      --data '{
        "model": "us.anthropic.claude-3-5-sonnet-20241022-v2:0",
        "model_id": "arn:aws:bedrock:us-east-1:6xxxxxxxxxx8:inference-profile/us.anthropic.claude-3-5-sonnet-20241022-v2:0",
        "messages": [{"role": "user", "content": "what llm are you"}]
      }'
    ```
    - **Expected Result**: The request completes successfully, and the response is returned by LiteLLM Proxy.

4. Start OpenHands using the following Docker command:
    ```bash
    docker --debug run -it --rm --pull=always \
      -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.14-nikolaik \
      -e LOG_ALL_EVENTS=true \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -p 3000:3000 \
      --add-host host.docker.internal:host-gateway \
      --name openhands-app \
      docker.all-hands.dev/all-hands-ai/openhands:0.14
    ```

5. Configure OpenHands with the following in the UI:
    - Custom model: `litellm_proxy/us.anthropic.claude-3-5-sonnet-20241022-v2:0`
    - Base URL: `http://0.0.0.0:4000`
    - API Key: `sk-xxxxxxxx`

6. Start a conversation in OpenHands.

---

### **Observed Behavior:**
OpenHands enters an infinite loop, throwing the following error repeatedly:

```plaintext
ValueError: invalid literal for int() with base 10: 'undefined'
  File "/app/openhands/server/listen.py", line 347, in websocket_endpoint
    latest_event_id = int(websocket.query_params.get('latest_event_id'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

---

### **Environment Details:**
- OpenHands Version: `0.14`
- LiteLLM Proxy Version: `1.52.10`
- Operating System: `MacOs`
- Hosting Environment: Docker
- AWS Region: `us-east-1`

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14

### Operating System

MacOS
