### ISSUE TITLE
Provide a docker-compose.yml file

### ISSUE THREAD

**Issue by s-celles** [All-Hands-AI/OpenHands#5392]
Hello,

Maybe providing a `docker-compose.yml` could simplify installation.

I tried this way (under Windows)

```yml
 services:
    openhands:
        stdin_open: true
        tty: true
        pull_policy: always
        environment:
            - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.14-nikolaik
            - LOG_ALL_EVENTS=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 3000:3000
        extra_hosts:
            - host.docker.internal:host-gateway
        container_name: openhands-app
        image: docker.all-hands.dev/all-hands-ai/openhands:0.14
```

but `docker compose up` raised

    openhands-app-  | exec /app/entrypoint.sh: no such file or directory

But manually running

    docker pull docker.all-hands.dev/all-hands-ai/runtime:0.14-nikolaik
    docker run -it --pull=always -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.14-nikolaik -e LOG_ALL_EVENTS=true -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 --add-host host.docker.internal:host-gateway --name openhands-app docker.all-hands.dev/all-hands-ai/openhands:0.14

works... it just need removing "\" at end of line (but I currently have no Anthropic credit for API usage ;-( )

Kind regards
