### ISSUE TITLE
[Feature Request]: Better frontend UI to display existing OpenHands instructions & MicroAgents

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#5538]
**What problem or use case are you trying to solve?**

Currently we implicitly uses `.openhands_instruction` and/or `.openhands/microagents` without the user knowing about it: https://github.com/All-Hands-AI/OpenHands/blob/6a6ce5f3ee090bf186045e965c6b5b1d88e27e70/openhands/runtime/base.py#L237

**Describe the UX of the solution you'd like**

We need to better design the FE UI so user can:
1. view repo instructions - with a link to tutorial about how to configure it
2. a button to add repo instructions (require the user to select the repo) - will automatically create a PR on user's repo
3. view microagents
4. add microagents: a button to ADD temporarily micro-agent instructions & a button to automatically starts a PR to contribute back to OpenHands

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

### If you find this feature request or enhancement useful, make sure to add a 👍 to the issue

**Comment by amirshawn** [comment]
Would it be possible to have a microagents management modal that could be trigger by a button at any time while using the system.  It would pop up and you could see all the microagents from your config and then edit your microagents, disable agents, add new agents etc... If we didn't want to use a database, the base config could be brought in when docker create the container and then any customization could be saved in the workspace and would only be temporary.  Just a couple thoughts.

**Comment by xingyaoww** [comment]
Updated proposal incorporating root-level microagents and template-based workflows:

### 1. Updated Directory Structure
```
OpenHands/
└── microagents/
    ├── README.md (documentation + contribution guidelines)
    ├── official/
    │   ├── knowledge/
    │   │   ├── github.yaml
    │   │   ├── npm.yaml
    │   │   └── docker.yaml
    │   └── templates/
    │       ├── pr_review.yaml
    │       ├── issue_triage.yaml
    │       └── feature_request.yaml
    └── community/
        ├── knowledge/
        │   ├── python_testing.yaml
        │   └── react_frontend.yaml
        └── templates/
            ├── bug_report.yaml
            └── code_review.yaml
```

### 2. Updated MicroAgent Format
```yaml
# Common fields for all microagents
name: agent_name
version: 1.0.0
author: username
category: development|testing|deployment|etc
agent: CodeActAgent  # Specifies which agent type this is compatible with
tags:
  - tag1
  - tag2
requires:
  - tool1
  - tool2

# For knowledge-based microagents
triggers:  # Optional, only for knowledge-based agents
  - trigger1
  - trigger2
conditions:  # Optional, for conditional activation
  repo_pattern: "org/repo-*"
  file_pattern: "*.py"
  
# For template-based microagents
template: |
  Can you look at this PR ${PR_URL}
  And then check out to branch ${BRANCH_NAME} which corresponds to that PR
  Then, read the diff against the main, understand the purpose of this PR, and then address the PR comments.
  ${USER_MESSAGE}

inputs:  # Required fields for template-based agents
  - name: PR_URL
    description: "URL of the pull request"
    type: string
    required: true
  - name: BRANCH_NAME
    description: "Name of the PR branch"
    type: string
    required: true
  - name: USER_MESSAGE
    description: "Additional context or instructions"
    type: string
    required: false

# Common fields continue
description: |
  Brief description of what this agent does...

capabilities:
  - Capability 1
  - Capability 2

guidelines:
  - Guideline 1
  - Guideline 2

examples:
  - description: "Example usage 1"
    code: |
      example command or template usage
```

### 3. Updated Frontend Modal Design
```
+----------------------------------------+
|  MicroAgent Management                [X]|
|----------------------------------------|
| Search: [                          ]    |
|----------------------------------------|
| Type:                                   |
| [Knowledge] [Templates] [All]           |
|----------------------------------------|
| Categories:                             |
| [Official] [Community] [Local] [All]    |
|----------------------------------------|
| Active Knowledge Agents:                |
| ☑️ GitHub Agent                         |
| ☑️ NPM Agent                            |
| ☐ Docker Agent                         |
|----------------------------------------|
| Available Templates:                    |
| + PR Review Template                    |
|   [Configure & Use]                     |
| + Issue Triage Template                 |
|   [Configure & Use]                     |
|----------------------------------------|
| [Add New Agent] [Submit to OpenHands]   |
+----------------------------------------+

Template Configuration Modal:
+----------------------------------------+
|  Configure PR Review Template        [X]|
|----------------------------------------|
| Required Inputs:                        |
| PR URL: [                           ]   |
| Branch: [                           ]   |
|----------------------------------------|
| Optional Inputs:                        |
| Message: [                           ]  |
|----------------------------------------|
| [Save as Preset] [Use Template]         |
+----------------------------------------+
```

### 4. Key Updates
1. **Two Types of MicroAgents**:
   - **Knowledge Agents**: Triggered by keywords/conditions
   - **Template Agents**: User-selected with input requirements

2. **Activation Methods**:
   - **Knowledge Agents**: Automatic via triggers/conditions
   - **Template Agents**: UI-based selection + input form

3. **Template Features**:
   - Input validation and type checking
   - Save configurations as presets
   - Variable substitution
   - Optional conversational input collection

4. **Implementation Notes**:
   - YAML format for better structure and validation
   - Clear separation between knowledge and template agents
   - Support for conditional activation
   - Preset management for frequently used templates

5. **Future Extensions**:
   - API endpoints for programmatic activation
   - Template chaining/workflows
   - Community rating and feedback system
   - Version control and compatibility checking

**Comment by xingyaoww** [comment]
☝️ OpenHands actually helped me brainstormed these :) 
https://www.all-hands.dev/share?share_id=b65f6c6d7053f4de31764ad850fd970fbae5219eaacf4c88a09b4fe201c3ad5c

**Comment by xingyaoww** [comment]
Updated proposal to clarify trigger mechanisms:

### 1. MicroAgent Types and Triggers

#### A. Knowledge-based MicroAgents
These agents provide specialized knowledge and can be triggered in two ways:

1. **Repository-based Triggers**:
```yaml
name: repo_instructions
agent: CodeActAgent
trigger_type: repository
trigger_pattern: "org/repo-*"  # Matches repository name pattern
description: "Repository-specific instructions and guidelines"
```

2. **Keyword-based Triggers**:
```yaml
name: github_agent
agent: CodeActAgent
trigger_type: keyword
triggers:
  - github
  - git
description: "GitHub-specific knowledge and operations"
```

#### B. Template-based MicroAgents
These require user selection and input:
```yaml
name: pr_review
agent: CodeActAgent
template_type: workflow
template: |
  Can you look at this PR ${PR_URL}
  And then check out to branch ${BRANCH_NAME}...
inputs:
  - name: PR_URL
    type: string
    required: true
```

### 2. Updated Directory Structure
```
OpenHands/
└── microagents/
    ├── README.md
    ├── official/
    │   ├── knowledge/
    │   │   ├── repo/  # Repository-triggered agents
    │   │   │   └── default.yaml  # Default repo instructions
    │   │   └── keyword/  # Keyword-triggered agents
    │   │       ├── github.yaml
    │   │       └── npm.yaml
    │   └── templates/
    │       └── workflows/
    │           ├── pr_review.yaml
    │           └── issue_triage.yaml
    └── community/
        ├── knowledge/
        │   ├── repo/
        │   │   └── python_project.yaml
        │   └── keyword/
        │       └── django.yaml
        └── templates/
            └── workflows/
                └── bug_report.yaml
```

### 3. Complete MicroAgent Format
```yaml
# Common fields
name: agent_name
version: 1.0.0
author: username
agent: CodeActAgent  # Required: specifies compatible agent type
category: development|testing|deployment|etc
tags:
  - tag1
  - tag2
requires:
  - tool1
  - tool2

# Type-specific fields (only one section should be present)

## For repository-triggered agents
trigger_type: repository
trigger_pattern: "org/repo-*"  # Supports glob patterns
priority: 100  # Higher number = higher priority when multiple patterns match

## For keyword-triggered agents
trigger_type: keyword
triggers:
  - keyword1
  - keyword2
file_patterns:  # Optional: only activate for specific files
  - "*.py"
  - "package.json"

## For template-based agents
template_type: workflow|snippet|guide
template: |
  Template text with ${VARIABLES}
inputs:
  - name: VARIABLE_NAME
    description: "What this variable is for"
    type: string|number|boolean|path
    required: true|false
    default: "optional default value"
    validation:  # Optional
      pattern: "^https://github.com/.*"
      min: 0  # For numbers
      max: 100  # For numbers

# Common fields continue
description: |
  Detailed description of what this agent does...

capabilities:
  - Capability 1
  - Capability 2

guidelines:
  - Guideline 1
  - Guideline 2

examples:
  - description: "Example usage 1"
    code: |
      example code or template usage
```

### 4. Updated Frontend Modal Design
```
+----------------------------------------+
|  MicroAgent Management                [X]|
|----------------------------------------|
| Search: [                          ]    |
|----------------------------------------|
| Active Knowledge Agents:                |
|----------------------------------------|
| Repository-based:                       |
| ☑️ Default Repo Instructions            |
| ☑️ Python Project Guidelines            |
|----------------------------------------|
| Keyword-based:                          |
| ☑️ GitHub Agent (git, github)           |
| ☑️ NPM Agent (npm, node)                |
|----------------------------------------|
| Available Templates:                    |
| + PR Review Workflow                    |
|   [Configure & Use]                     |
| + Issue Triage Template                 |
|   [Configure & Use]                     |
|----------------------------------------|
| [Add New Agent] [Submit to OpenHands]   |
+----------------------------------------+
```

### 5. Activation Flow

1. **Repository-based Agents**:
```mermaid
graph TD
    A[New Repository] --> B{Check repo name}
    B --> C{Match patterns}
    C --> D[Sort by priority]
    D --> E[Load matching agents]
```

2. **Keyword-based Agents**:
```mermaid
graph TD
    A[User input] --> B{Check keywords}
    B --> C{Check file patterns}
    C --> D[Activate matching agents]
```

3. **Template-based Agents**:
```mermaid
graph TD
    A[User selects template] --> B[Show input form]
    B --> C{Validate inputs}
    C --> D[Process template]
    D --> E[Execute workflow]
```

This updated design provides a clear separation between different trigger mechanisms while maintaining a consistent structure for all microagents. The YAML format allows for easy validation and processing, while the directory structure makes it clear how different types of agents are organized and activated.
