### ISSUE TITLE
[Resolver] Git LFS Support

### ISSUE THREAD

**Issue by chetanpepper** [All-Hands-AI/OpenHands#6156]
**What problem or use case are you trying to solve?**
I have a repo with a lot of data files stored in Git LFS. It looks like OpenHands clones the repo [here](https://github.com/All-Hands-AI/OpenHands/blob/c411a29db408564cf1935e0fe0165e2b4362b270/openhands/resolver/resolve_issue.py#L385).

I'm running on Github Actions and have tried passing GIT_LFS_SKIP_SMUDGE: 1 as an environment variable, but it doesn't seem to have an effect.

The Github action ends up failing due to lack of storage space.

**Describe the UX of the solution you'd like**
Environment variable that can be passed to the container to skip large LFS files on clone.

**Do you have thoughts on the technical implementation?**
Add an environment variable to the workflow that will accept parameters to git clone, `GIT_LFS_SKIP_SMUDGE` and `--depth` most importantly

**Describe alternatives you've considered**
I could fork openhands and modify the `clone` command.

**Additional context**
Workflow file:

```
name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  GIT_LFS_SKIP_SMUDGE: '1'
  
jobs:
  call-openhands-resolver:
    uses: All-Hands-AI/OpenHands/.github/workflows/openhands-resolver.yml@main
    with:
      macro: ${{ vars.OPENHANDS_MACRO || '@openhands-agent' }}
      max_iterations: ${{ fromJson(vars.OPENHANDS_MAX_ITER || 50) }}
      base_container_image: ${{ vars.OPENHANDS_BASE_CONTAINER_IMAGE || '' }}
      LLM_MODEL: ${{ vars.LLM_MODEL || 'anthropic/claude-3-5-sonnet-20241022' }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
```
