### ISSUE TITLE
[Bug]: Failed to Use Azure OpenAI API to run WebArena Evaluation

### ISSUE THREAD

**Issue by wxl-lxw** [All-Hands-AI/OpenHands#6389]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

I'm trying to run WebArena evaluation following [this guide](https://github.com/All-Hands-AI/OpenHands/tree/main/evaluation/benchmarks/webarena#run-evaluation), and when executing command

`bash evaluation/benchmarks/webarena/scripts/run_infer.sh`

It throws an error that

```
usage: run_infer.py [-h] [-v] [--config-file CONFIG_FILE] [-d DIRECTORY] [-t TASK] [-f FILE] [-c AGENT_CLS] [-i MAX_ITERATIONS]
                    [-b MAX_BUDGET_PER_TASK] [--eval-output-dir EVAL_OUTPUT_DIR] [--eval-n-limit EVAL_N_LIMIT]
                    [--eval-num-workers EVAL_NUM_WORKERS] [--eval-note EVAL_NOTE] [-l LLM_CONFIG] [-n NAME] [--eval-ids EVAL_IDS]
                    [--no-auto-continue]
run_infer.py: error: argument -l/--llm-config: expected one argument
```

My `config.toml` file is shown below:

```toml
[core]
workspace_base="./workspace"

[llm]
model="gpt-4o"
api_key="xxx"
embedding_model="azureopenai"
base_url="https://yyy.openai.azure.com/"
embedding_deployment_name="azure/gpt-4o"
api_version="2024-02-01"
```

Is there any wrong with the LLM configuration?

### OpenHands Installation

Development workflow

### OpenHands Version

0.20.0

### Operating System

Linux
