### ISSUE TITLE
[Bug]: Fails to create files in workspace.

### ISSUE THREAD

**Issue by Darkyere** [All-Hands-AI/OpenHands#7525]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

Setup linux docker container for Ollama and OpenHands.

Docker-compose.yaml

```
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: no
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
   openhands-app:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.30
    container_name: openhands-app
    restart: no
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.30-nikolaik
      - LOG_ALL_EVENTS=true
    ports:
      - "3333:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./openhands-state:/.openhands-state
    extra_hosts:
      - "host.docker.internal:host-gateway"
    pull_policy: always
```

----

Connected with 

![Image](https://github.com/user-attachments/assets/97da4386-b910-4bb8-aa33-de1f2f0d6020)

----

Error in openhands web interface

![Image](https://github.com/user-attachments/assets/c023087e-d2cd-48e7-847a-ae9c17caed3c)

What should i do to get this fixed?

### OpenHands Installation

Docker command in README

### OpenHands Version

30

### Operating System

Linux
