### ISSUE TITLE
Improve docker file to reduce data transfer on project update

### ISSUE THREAD

**Issue by cwirz** [All-Hands-AI/OpenHands#7664]
**What problem or use case are you trying to solve?**
Reduce the amount of data that is transferred when a new version is released by doing docker pull.

**Describe the UX of the solution you'd like**
Optimising the dockerfile to have the docker layers that are updated to come later in the docker build process so the developers only need to pull the last layers.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by mamoodi** [comment]
This was done at some point but not sure if it was fully optimized. Thanks for the suggestion.

**Comment by cwirz** [comment]
It seems like this was fixed on the main branch? @mamoodi

**Comment by cwirz** [comment]
Now its great, new version pull with max 100mb for me.

```sh
docker pull docker.all-hands.dev/all-hands-ai/runtime:main-nikolaik
docker compose pull
```

```yml
services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:main
    stdin_open: true
    tty: true
    pull_policy: always
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE
      - LOG_ALL_EVENTS=true
      - SANDBOX_USER_ID
      - WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $OPENHANDS_STATE:/.openhands-state
      - $WORKSPACE_BASE:/opt/workspace_base:rw
    ports:
      - "3963:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    external: true
    name: $NETWORK_NAME
```
