### ISSUE TITLE
[Bug]: Runtime initialization fails on WSL

### ISSUE THREAD

**Issue by avi12** [All-Hands-AI/OpenHands#7830]
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

`config.toml`
```toml
[core]
workspace_base="/mnt/d/repositories/extension/auto-detect-new-youtube-videos"
```
LLM: `gemini-2.5-pro-preview-03-25`

### OpenHands Installation

Development workflow

### OpenHands Version

`main`, https://github.com/All-Hands-AI/OpenHands/commit/20d3766451959eb7d416f895d124afe411d137a1

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

[openhands_2025-04-12.log](https://github.com/user-attachments/files/19719417/openhands_2025-04-12.log)
