### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by miracuruzrh** [All-Hands-AI/OpenHands#8416]
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

Hello,

I have set up OpenHands on my Proxmox LXC Docker server (Debian 12 Bookworm).  
This server runs on IP `192.168.1.16`. The OpenWebUI for my Ollama installation is also running on this IP.  
OpenWebUI connects to my Ollama instance at `192.168.1.100`.

I start the OpenHands container and create the example project *Hello World app*.  
It spins up the `openhands-runtime...` containers, but after a while it stops and throws an error.

**Error message:**
> RuntimeError: There was an unexpected error while running the agent. Please report this error to the developers. Your session ID is 84bd885bb5044c1187345c78141c9d0c. Error type: InternalServerError

At this point, I'm out of ideas, so I’m opening this issue for support.

Please let me know if further information is needed.

Best regards,  
Simon

---

**My `docker compose` configuration:**  
```yml
services:
  all-hands-ai:
    image: 'docker.all-hands.dev/all-hands-ai/openhands:0.21'
    container_name: openhands-app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
    volumes:
      - '.openhands-state:/.openhands-state'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - LOG_ALL_EVENTS=true
      - 'SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.21-nikolaik'
      - LLM_API_KEY=REDACTED
      - LLM_BASE_URL=192.168.1.100:11434
    pull_policy: always
    tty: true
    stdin_open: true
    restart: unless-stopped
```

### OpenHands Installation

Docker command in README

### Operating System

None
