### ISSUE TITLE
[Bug]: cannot set config file path under docker

### ISSUE THREAD

**Issue by createthis** [All-Hands-AI/OpenHands#8435]
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

I can't figure out how to set the config file path under docker. I'm trying to set up an MCP server. On my docker host, I've placed it under `~/.openhands/config.toml`:

```toml
[mcp]
# SSE Servers - External servers that communicate via Server-Sent Events
sse_servers = [
    "http://host.docker.internal:3002/mcp",
]
```

I've mapped it into the docker container with:

```bash
    -v ~/.openhands/config.toml:/.openhands/config.toml \
```

I see `--config-file` in the cli args, but this doesn't seem to work from docker:

```bash
    -e AGENT_CONFIG_FILE=/.openhands/config.toml \
```

I also tried:

```bash
    -e CONFIG_FILE=/.openhands/config.toml \
```

With all the documentation talking about `config.toml`, you'd think this would be a thing. What am I doing wrong?

Thanks!

### OpenHands Installation

Docker command in README

### OpenHands Version

e26ca14-nikolaik

### Operating System

MacOS
