### ISSUE TITLE
[Bug]: CLI mode with Docker can't load `config.toml` file

### ISSUE THREAD

**Issue by KennyDizi** [All-Hands-AI/OpenHands#9177]
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

Whenever I try to use OpenHands in CLI mode with Docker, it always asks about LLM settings.

Here is my `config.toml` file

```toml
[core]
search_api_key = "tvly-***"
reasoning_effort = "high"
platform = "linux/amd64" # Can be linux/amd64 or linux/arm64

[llm]
api_key = "sk-proj-***"
# API base URL (For Headless / CLI only -  In Web this is overridden by Session Init)
#base_url = ""
provider = "openai" # Can be openai, anthropic, deepseek, openrouter
# Model to use. (For Headless / CLI only -  In Web this is overridden by Session Init)
model = "openai/o3"
```

Here is the command that I used to run OpenHands CLI mode with Docker:

```bash
docker run -it --rm --pull=always \
        -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.43.0-nikolaik \
        -e LOG_ALL_EVENTS=true \
        -e SANDBOX_USER_ID=$(id -u) \
        -e SANDBOX_VOLUMES=$SANDBOX_VOLUMES \
        -e RUNTIME_MOUNT=$RUNTIME_MOUNT \
        -e LLM_API_KEY=$LLM_API_KEY \
        -e LLM_PROVIDER=$LLM_PROVIDER \
        -e LLM_MODEL=$LLM_MODEL \
        -e AGENT_MEMORY_ENABLED=$AGENT_MEMORY_ENABLED \
        -e LLM_CACHING_PROMPT=$LLM_CACHING_PROMPT \
        -e AGENT_ENABLE_THINK=$AGENT_ENABLE_THINK \
        -e LLM_NUM_RETRIES=$LLM_NUM_RETRIES \
        -e AGENT_ENABLE_MCP=$AGENT_ENABLE_MCP \
        -e CORE_PLATFORM=$CORE_PLATFORM \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v ~/.openhands-state:/.openhands-state \
        -v $RUNTIME_MOUNT \
        -w /workspace \
        -p 3080:3080 \
        --add-host host.docker.internal:host-gateway \
        --network oha-network \
        --name "${CONTAINER_NAME}" \
        docker.all-hands.dev/all-hands-ai/openhands:0.43.0 \
        python3 -m openhands.cli.main --override-cli-mode true
```

Here is the result

![Image](https://github.com/user-attachments/assets/7488a279-05e7-48a6-9625-1b342d8fcf48)

Expected behaviour: If we have already specified the configurations in the `config.toml` file or via environment variables, we shouldn't ask for it again when starting OpenHands.

### OpenHands Installation

Docker command in README

### OpenHands Version

v0.42, v0.43

### Operating System

macOS
